name: Release package

on:
  workflow_dispatch:
    inputs:
      version:
        type: string

jobs:
  releasePackage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone project
      uses: actions/checkout@v4
      with:
        path: dd-sdk-unity

    - name: Clone deployment repo
      uses: actions/checkout@v4
      with:
        repository: Laerdal/datadog-unity-package
        path: datadog-unity-package
        token: ${{ secrets.DATADOG_UNITY_PACKAGE_PAT }}
    
    - name: Install PIP packages
      run: |
        cd dd-sdk-unity/tools/scripts 
        pip install -r requirements.txt
    
    - name: Run release script
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: python release_package.py --version ${{ inputs.version }} --dest $WORKSPACE/datadog-unity-package --skip-manual-verify
