name: Release package

on:
  workflow_dispatch:
    inputs:
      version:
        type: string

jobs:
  releasePackage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone project
      uses: actions/checkout@v4

    - name: Clone deployment repo
      uses: actions/checkout@v4
      with:
        repository: Laerdal/datadog-unity-sdk
        path: datadog-unity-sdk

    
    - name: Install PIP packages
      run: pip install -r tools/scripts/requirements.txt
    
    - name: Run release script
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        cd tools/scripts
        python release_package.py --version ${{ inputs.version }} --dest git@github.com:Laerdal/datadog-unity-package --skip-manual-verify
