name: Release package

on:
  workflow_dispatch:
    inputs:
      version:
        type: string

jobs:
  releasePackage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone project
      uses: actions/checkout@v4
      with:
        path: dd-sdk-unity

    - name: Clone deployment repo
      uses: actions/checkout@v4
      with:
        repository: Laerdal/datadog-unity-package
        path: datadog-unity-package
        token: ${{ secrets.DATADOG_UNITY_PACKAGE_PAT }}
    
    - name: Install PIP packages
      run: |
        cd ${{ github.workspace }}/dd-sdk-unity/tools/scripts
        pip install -r requirements.txt

    - name: Set token in project repo
      run: |
        cd ${{ github.workspace }}/dd-sdk-unity
        git remote set-url origin https://${{ secrets.DATADOG_UNITY_PACKAGE_PAT }}@github.com/Laerdal/dd-sdk-unity

    - name: Set token in deployment repo
      run: |
        cd ${{ github.workspace }}/datadog-unity-package
        git remote set-url origin https://${{ secrets.DATADOG_UNITY_PACKAGE_PAT }}@github.com/Laerdal/datadog-unity-package
    
    - name: Run release script
      env:
        GITHUB_TOKEN: ${{ secrets.DATADOG_UNITY_PACKAGE_PAT }}
      run: |
        cd ${{ github.workspace }}/dd-sdk-unity/tools/scripts
        python release_package.py --version ${{ inputs.version }} --dest ${{ github.workspace }}/datadog-unity-package --skip-manual-verify
